// This is file is autogenerated. Do not edit.
public class App {
  public static var screens: [Form.screen] = [    Form.screen(
      no: 1,
      name: "01-WELCOME",
      sections: [
        Form.section(name: "Вітаємо в CHAT!",
          rows: [ 
            Form.row(no: 1, desc: "Реєстрація", rico: ("more","02-REG")), 
            Form.row(no: 2, desc: "Авторизація", rico: ("more","")), 
            Form.row(no: 3, desc: "Імпорт", rico: ("more","")),  ]) ]),
    Form.screen(
      no: 2,
      name: "02-REG",
      sections: [
        Form.section(name: "Реєстрація",
          rows: [ 
            Form.row(no: 1, desc: "Позивний", rico: ("more","")), 
            Form.row(no: 2, desc: "Пароль", rico: ("more","")), 
            Form.row(no: 3, desc: "Продовжити", rico: ("more","03-PROFILE")),  ]) ]),
    Form.screen(
      no: 4,
      name: "04-PRIVACY",
      sections: [
        Form.section(name: "Приватність",
          rows: [ 
            Form.row(no: 1, desc: "Синхронізація контактів з iOS", rico: ("more","")), 
            Form.row(no: 2, desc: "Блокування невідомих", rico: ("more","")), 
            Form.row(no: 3, desc: "Ділитися контактами з iOS", rico: ("more","")), 
            Form.row(no: 4, desc: "Заблоковані корістувачі", rico: ("more","")), 
            Form.row(no: 5, desc: "Номер телефону", rico: ("more","")), 
            Form.row(no: 6, desc: "Email", rico: ("more","")), 
            Form.row(no: 7, desc: "Видимість в загальному каталозі", rico: ("more","")), 
            Form.row(no: 8, desc: "Відвідини та стан мережі", rico: ("more","")), 
            Form.row(no: 9, desc: "Фото профілю", rico: ("more","")), 
            Form.row(no: 10, desc: "Виклики", rico: ("more","")), 
            Form.row(no: 11, desc: "Голосові повідомлення", rico: ("more","")), 
            Form.row(no: 12, desc: "Пересилання повідомлень", rico: ("more","")), 
            Form.row(no: 13, desc: "Додавання мене в групах", rico: ("more","")), 
            Form.row(no: 14, desc: "Звіт про прочитання", rico: ("more","")), 
            Form.row(no: 15, desc: "Індикатор набору тексту", rico: ("more","")), 
            Form.row(no: 16, desc: "Папки для чатів", rico: ("more","05-CONTACT")), 
            Form.row(no: 17, desc: "Таймер автовидалення", rico: ("more","")),  ]) ]),
    Form.screen(
      no: 5,
      name: "05-CONTACT",
      sections: [
        Form.section(name: "Контакт",
          rows: [ 
            Form.row(no: 1, desc: "Чати", rico: ("more","")), 
            Form.row(no: 2, desc: "Дзвінки", rico: ("more","")), 
            Form.row(no: 3, desc: "Відеодзвінки", rico: ("more","")), 
            Form.row(no: 4, desc: "User ID", rico: ("more","")), 
            Form.row(no: 5, desc: "Видалити контакт", rico: ("more","")), 
            Form.row(no: 6, desc: "Очистити бесіди", rico: ("more","")), 
            Form.row(no: 7, desc: "Заблокувати контакт", rico: ("more","")), 
            Form.row(no: 8, desc: "Рівень підтверження", rico: ("more","")), 
            Form.row(no: 9, desc: "Відкритий ключ", rico: ("more","")), 
            Form.row(no: 10, desc: "Контактна інформація", rico: ("more","")), 
            Form.row(no: 11, desc: "Вимкнути сповіщення", rico: ("more","")), 
            Form.row(no: 12, desc: "Зникаючі повідомлення", rico: ("more","")), 
            Form.row(no: 13, desc: "Pin Chat", rico: ("more","")), 
            Form.row(no: 14, desc: "Папки", rico: ("more","")), 
            Form.row(no: 15, desc: "Файли контакту", rico: ("more","")),  ]) ]),
    Form.screen(
      no: 3,
      name: "03-PROFILE",
      sections: [
        Form.section(name: "Налаштування профілю",
          rows: [ 
            Form.row(no: 1, desc: "Profile ID", rico: ("more","")), 
            Form.row(no: 2, desc: "Відкритий ключ", rico: ("more","")), 
            Form.row(no: 3, desc: "Налаштування ключів", rico: ("more","")), 
            Form.row(no: 4, desc: "Налаштування серверів", rico: ("more","")), 
            Form.row(no: 5, desc: "Прив'язаний номер", rico: ("more","")), 
            Form.row(no: 6, desc: "Прив'язаний E-Mail", rico: ("more","")), 
            Form.row(no: 7, desc: "Блокування паролем", rico: ("more","")), 
            Form.row(no: 8, desc: "Приватність", rico: ("more","04-PRIVACY")), 
            Form.row(no: 9, desc: "Export ID", rico: ("more","")), 
            Form.row(no: 10, desc: "Сховище і дані", rico: ("more","")), 
            Form.row(no: 11, desc: "Видалити дані ID", rico: ("more","")), 
            Form.row(no: 12, desc: "Видалити профіль", rico: ("more","")), 
            Form.row(no: 13, desc: "Версія", rico: ("more","")), 
            Form.row(no: 14, desc: "Параметри", rico: ("more","")), 
            Form.row(no: 15, desc: "Підтримати", rico: ("more","")), 
            Form.row(no: 16, desc: "Політика конфіденційності", rico: ("more","")), 
            Form.row(no: 17, desc: "Умови використання", rico: ("more","")), 
            Form.row(no: 18, desc: "Ліцензії", rico: ("more","")), 
            Form.row(no: 19, desc: "Довідка", rico: ("more","")),  ]) ]),
   ]
}
