// This file is autogenerated. Do not edit.

import SwiftASN1
import Crypto
import Foundation

@usableFromInline indirect enum A: DERParseable, DERSerializable, Hashable, Sendable {
    case v(V)
    case list(List)
    @inlinable init(derEncoded rootNode: ASN1Node) throws {
        switch rootNode.identifier {
            case V.defaultIdentifier:
                self = .v(try V(derEncoded: rootNode))
            case List.defaultIdentifier:
                self = .list(try List(derEncoded: rootNode))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer) throws {
        switch self {
            case .v(let v): try coder.serialize(v)
            case .list(let list): try coder.serialize(list)
        }
    }

}
